version: '3'
services:
  backend:
    build: /backend
    ports:
      - "8000:80"
    environment:
      - MONGODB_CONNSTRING=mongodb://VerteilteSystemeLabor:ws_22_23_vs@mongodb
      - MONGODB_USER=VerteilteSystemeLabor
      - MONGODB_PW=ws_22_23_vs
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=VerteilteSystemeLabor
      - MONGO_INITDB_ROOT_PASSWORD=ws_22_23_vs
  frontend:
    build: /vue frontend/vue-frontend
    ports:
      - "8008:8008"