FROM node:lts-alpine

# install simple http server for serving static content
#RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
#RUN npm run dev

EXPOSE 8008
CMD [ "npm", "run" , "dev" ]

#docker build -t dockervueapp -f Dockerfile .
#docker run -it -p 8010:8008 --rm --name dockervueappContainer dockervueapp
